// API Configuration
export const API_CONFIG = {
  // Base URL for API calls - production server
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://18.169.19.110:8000/admin',
  
  // Default timeout for API requests (in milliseconds)
  TIMEOUT: 10000,
  // Extended timeout for analytics requests (2 minutes)
  ANALYTICS_TIMEOUT: 120000,
  
  // Default headers
  DEFAULT_HEADERS: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
  },
  
  // API endpoints
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/login',
      LOGOUT: '/auth/logout',
      REFRESH: '/auth/refresh',
      VERIFY_2FA: '/auth/verify-2fa',
    },
    PASSWORD: {
      FORGOT: '/forgot-password',
      RESET: '/reset-password',
      CHANGE: '/change-password',
    },
    PERMISSIONS: {
      CREATE: '/permissions/create',
      LIST: '/permissions',
      ASSIGN: '/permissions/assign',
      GET_BY_ADMIN: '/admins/:adminId/permissions',
      UPDATE: '/permissions/:permissionId',
      DELETE: '/permissions/:permissionId',
    },
    ROLES: {
      CREATE: '/roles/create',
      LIST: '/roles',
      ASSIGN: '/roles/assign',
      GET_BY_ADMIN: '/admins/:adminId/roles',
      ASSIGN_PERMISSIONS: '/roles/permissions/assign',
      GET_ROLE_PERMISSIONS: '/roles/:roleId/permissions',
      UPDATE: '/roles/:roleId',
      DELETE: '/roles/:roleId',
    },
    USERS: {
      LIST: '/users',
      CREATE: '/users',
      UPDATE: '/users/:id',
      DELETE: '/users/:id',
      PAUSE: '/users/:id/pause',
      DETAILS: '/users/:id',
      BAN: '/users/:id/ban',
      MODERATION_ACTIONS: '/users/:id/moderation-actions',
      UNBAN: '/users/:id/unban',
    },
    ADMIN_PROFILE: {
      PROFILE: '/admin-profile',
      PROFILE_AVATAR: '/admin-profile/avatar',
      PROFILE_PASSWORD: '/admin-profile/password',
      PROFILE_PASSWORD_VERIFY_OTP: '/admin-profile/password/verify-otp',
      PROFILE_PASSWORD_RESET_REQUEST: '/admin-profile/password/reset-request',
      PROFILE_PASSWORD_RESET: '/admin-profile/password/reset',
      PROFILE_PREFERENCES: '/admin-profile/preferences',
      PROFILE_ACTIVITY: '/admin-profile/activity',
      PROFILE_2FA_SETUP: '/admin-profile/2fa/setup',
      PROFILE_2FA_ENABLE: '/admin-profile/2fa/enable',
      PROFILE_2FA_DISABLE: '/admin-profile/2fa/disable',
    },
    PRODUCTS: {
      LIST: '/products',
      CREATE: '/products',
      UPDATE: '/products/:id',
      DELETE: '/products/:id',
      DETAILS: '/products/:id',
    },
    CONTENT: {
      PAGES: '/content/pages',
      UPDATE_PAGE: '/content/pages/:id',
      SETTINGS: '/content/settings',
      ABOUT_US: '/about-us',
      ABOUT_US_SECTIONS: '/about-us/sections',
      ABOUT_US_TEAM_MEMBERS: '/about-us/team-members',
      ABOUT_US_MAIN_IMAGE: '/about-us/upload-main-image',
      PRIVACY_POLICY: '/privacy-policy',
    },
    INDEX_PAGE: {
      MAIN: '/index-page',
      SECTIONS: '/index-page/sections',
      SECTION: '/index-page/sections/:id',
      SECTION_STATUS: '/index-page/sections/:id/status',
      REORDER_SECTIONS: '/index-page/sections/reorder',
    },
    DASHBOARD: {
      MAIN: '/dashboard',
      STATS: '/dashboard/stats',
      STATS_SUMMARY: '/dashboard/stats/summary',
      ACTIVITY: '/dashboard/activity',
      USER_GROWTH: '/dashboard/analytics/user-growth',
      USER_GROWTH_SYNC: '/dashboard/analytics/user-growth/sync',
      ACTIVE_USERS: '/dashboard/analytics/active-users',
      CONVERSIONS: '/dashboard/analytics/conversions',
      REVENUE: '/dashboard/analytics/revenue',
      CONVERSATION_ANALYTICS: '/dashboard/analytics/conversation-analytics',
      APP_STORE_INSTALL_STATS: '/dashboard/analytics/app-store-install-stats',
    },
    ENQUIRIES: {
      LIST: '/enquiries',
      CREATE: '/enquiries',
      UPDATE: '/enquiries/:id',
      DELETE: '/enquiries/:id',
      REPLY: '/enquiries/:id/reply',
      STATS: '/enquiries/stats/overview',
      FILTER_OPTIONS: '/enquiries/filter-options',
      EXPORT: '/enquiries/export',
    },
    REPORTS: {
      LIST: '/reports',
      CREATE: '/reports',
      UPDATE: '/reports/:id',
      DELETE: '/reports/:id',
      DETAILS: '/reports/:id',
      STATS: '/reports/stats/overview',
      FILTER_OPTIONS: '/reports/filter-options',
      EXPORT: '/reports/export',
    },
    CONTACT: {
      SUBMIT: '/contact',
    },
    FAQS: {
      LIST: '/faqs',
      CREATE: '/faqs',
      UPDATE: '/faqs/:id',
      DELETE: '/faqs/:id',
      DETAILS: '/faqs/:id',
      STATUS: '/faqs/:id/status',
    },
    SITE_SETTINGS: {
      INITIALIZE: '/site-settings/initialize',
      GET: '/site-settings/main',
      UPDATE: '/site-settings/main',
    },
    ADMIN_MANAGEMENT: {
      LIST: '/admin-management',
      STATS: '/admin-management/stats',
      CREATE: '/admin-management',
      UPDATE: '/admin-management/:id',
      DELETE: '/admin-management/:id',
      TOGGLE_STATUS: '/admin-management/:id/toggle-status',
      CHANGE_PASSWORD: '/admin-management/:id/password',
      DETAILS: '/admin-management/:id',
    },
    CAMPAIGNS: {
      LIST: '/campaigns',
      STATS: '/campaigns/stats',
      CREATE: '/campaigns',
      UPDATE: '/campaigns/:id',
      DELETE: '/campaigns/:id',
      DETAILS: '/campaigns/:id',
      RUN: '/campaigns/:id/run',
      CANCEL: '/campaigns/:id/cancel',
      STATUS: '/campaigns/:id/status',
      SCHEDULER_STATUS: '/campaigns/scheduler/status',
      SCHEDULER_REFRESH: '/campaigns/scheduler/refresh',
      SCHEDULER_CHECK: '/campaigns/scheduler/check',
      // Email tracking endpoints
      FAILED_EMAILS: '/campaigns/:id/failed-emails',
      RETRY_FAILED: '/campaigns/:id/retry-failed',
      DETAILED_STATS: '/campaigns/:id/detailed-stats',
      RETRY_TRIGGER: '/campaigns/retry/trigger',
      RETRY_STATS: '/campaigns/retry/stats',
    },
    FACE_VERIFICATIONS: {
      LIST: '/face-verifications',
      PENDING: '/face-verifications/pending',
      DETAILS: '/face-verifications/:id',
      APPROVE: '/face-verifications/:id/approve',
      REVERIFY: '/face-verifications/users/:userId/reverify',
      FLAGGED_USERS: '/face-verifications/flagged/users',
      STATISTICS: '/face-verifications/statistics',
      RETRY_HISTORY: '/face-verifications/group/:groupId/retries',
      MANUAL_VERIFICATION: '/face-verifications/users/:userId/manual-verification',
    },
    ACTIVITY_LOGS: {
      LIST: '/activity-logs',
      USERS: '/activity-logs/users',
    },
  },
} as const;

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

// API Error Types
export const API_ERROR_TYPES = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const; 
